= prediction endpoint

== /prediction

http://127.0.0.1:5000/predict
Local Host

The prediction endpoint will provide a predicted gradepoint average based on various demographic factors.

==== Authorization requirements: `none`.

=== GET /predict



Path parameters


[%header, cols=4*]
|===
| Query string parameter| Required / optional | Description | Type 
| sex | Required | Binary F (female) or M (Male) | string
| age | Required | Numeric 15 - 22 | integer 
| address | Required | Binary U (urban) or R (rural) | string
| famsize | Required | Binary LE3 (less or equal to 3) or GT3 (greater than 3) | string
| pstatus | Required | Parent cohabitation status. Binary T (together) or A (apart) | string
| medu | Required | Mother's education. Numeric 0 (none), 1 (primary education 4th grade), 2 (5th to 9th grade), 3 (secondary education), or 4 (higher education) | integer
| pedu | Required | Father's education. Numeric 0 (none), 1 (primary education 4th grade), 2 (5th to 9th grade), 3 (secondary education), or 4 (higher education) | integer
| traveltime | Required | Home to school travel time 1 (<15 minutes), 2 (15 to 30 minutes), 3 (30 minutes to 1 hour), 4 (>1 hour) | integer 
| studytime | Required | Weekly Study time. 1 (<2 hours), 2 ( 2 to 5 hours), 3 (5 to 10 hours), 4 (>10 hours) | integer 
| failures | Required | Numeric number of past class failures | integer 
| schoolsup | Required | Extra educational support. Binary yes or no | string
| famsup | Required | Family educational support, Binary yes or no | string
| paid | Required | Extra paid classes within the course subject. Binary yes or no | string
| absences | Required | Numeric number of school absences | integer
| activities | Required | Extra-carricular activities. Binary yes or no | string
| higher | Required | Wants to take higher education. Binary yes or no | string
| internet | Required | Internet access at home. Binary yes or no | string
| romantic | Required | Involved in a romantic relationship. Binary yes or no | string
| famrel | Required | Quality of family relationship. Numeric from 1 (very bad) to 5 (excellent) | integer 
| freetime | Required | Free time after school. Numeric from 1 (very low) to 5 (very high) | integer
| goout | Required | Time spent going out with friends. Numeric from 1 (very low) to 5 (very high) | integer 
| Dalc | Required | Workday alcohol consumption. Numeric from 1 (very low) to 5 (very high) | integer
| Walc | Required | Weekend alcohol consumption. Numeric from 1 (very low) to 5 (very high) | integer
| health | Required | Current health status. Numeric from 1 (very bad) to 5 (very good) | integer
|=== 

==== Examples

*cURL*
....
curl --location --request GET 'http://127.0.0.1:5000/predict' \
--header 'Content-Type: text/plain' \
--data-raw '{"sex":"F","age":20,"address":"U","famsize":"GT3","Pstatus":"A","Medu":4,"Fedu":1,"traveltime":1,"studytime":2,"failures":0,"schoolsup":"no","famsup":"yes","paid":"no","absences":0,"activities":"no","higher":"yes","internet":"yes","romantic":"no","famrel":2,"freetime":3,"goout":1,"Dalc":2,"Walc":2,"health":4}
'
....

*HTTP*
....
GET /predict HTTP/1.1
Host: 127.0.0.1:5000
Content-Type: text/plain
Content-Length: 312

{"sex":"F","age":20,"address":"U","famsize":"GT3","Pstatus":"A","Medu":4,"Fedu":1,"traveltime":1,"studytime":2,"failures":0,"schoolsup":"no","famsup":"yes","paid":"no","absences":0,"activities":"no","higher":"yes","internet":"yes","romantic":"no","famrel":2,"freetime":3,"goout":1,"Dalc":2,"Walc":2,"health":4}
....

*Python*
....
import requests

url = "http://127.0.0.1:5000/predict"

payload = "{\"sex\":\"F\",\"age\":20,\"address\":\"U\",\"famsize\":\"GT3\",\"Pstatus\":\"A\",\"Medu\":4,\"Fedu\":1,\"traveltime\":1,\"studytime\":2,\"failures\":0,\"schoolsup\":\"no\",\"famsup\":\"yes\",\"paid\":\"no\",\"absences\":0,\"activities\":\"no\",\"higher\":\"yes\",\"internet\":\"yes\",\"romantic\":\"no\",\"famrel\":2,\"freetime\":3,\"goout\":1,\"Dalc\":2,\"Walc\":2,\"health\":4}\r\n"
headers = {
  'Content-Type': 'text/plain'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)
....

==== Responses

`200` success

....
{
    "Prediction": 13.0
}
....

`404` not found
....
<!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try
	again.</p>
....


`500` request not found

missing parameter
....
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or
	there is an error in the application.</p>
....
